//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.SqlTypes;
using ShenZhen.Lottery.Public;

namespace ShenZhen.Lottery.Model
{
    using System;
    using System.Collections.Generic;

    public partial class BankInfo
    {

        public int Id { get; set; }
        public int UserId { get; set; }
        public string BankName { get; set; }
        public string Provience { get; set; }
        public string City { get; set; }
        public string ZhiHangName { get; set; }
        public string BankNum { get; set; }
        public string RealName { get; set; }
        public int Type { get; set; }                   //1.出款  2.入款
        public bool Status { get; set; }                //1.启用 0.停用
        public System.DateTime SubTime { get; set; }

        public int? GroupId { get; set; }

        public UserInfo user { get; set; }


        //----------------------扩展字段

        //类型
        public string ShowType
        {
            get
            {
                if (Type == 1)
                {
                    return "出款";
                }
                else if (Type == 2)
                {
                    return "入款";
                }

                return "";
            }
        }

        //银行图片
        public string BankPicSrc
        {
            get
            {
                string result = "";

                if (BankName == "微信支付")
                {
                    result = "46_25.png";
                }
                else if (BankName == "招商银行")
                {
                    result = "zsyh.png";
                }
                else if (BankName == "平安银行")
                {
                    result = "payh.png";
                }
                else if (BankName == "广发银行")
                {
                    result = "gfyh.png";
                }
                else if (BankName == "中国银行")
                {
                    result = "zgyh.png";
                }
                else if (BankName == "光大银行")
                {
                    result = "gdyh.png";
                }
                else if (BankName == "中信银行")
                {
                    result = "zxyh.png";
                }
                else if (BankName == "工商银行")
                {
                    result = "gsyh.png";
                }
                else if (BankName == "农业银行")
                {
                    result = "nyyh.png";
                }
                else if (BankName == "建设银行")
                {
                    result = "jsyh.png";
                }
                else if (BankName == "交通银行")
                {
                    result = "jtyh.png";
                }
                else if (BankName == "邮政银行")
                {
                    result = "yzyh.png";
                }
                else if (BankName == "兴业银行")
                {
                    result = "xyyh.png";
                }
                else if (BankName == "民生银行")
                {
                    result = "msyh.png";
                }
                else if (BankName == "浦发银行")
                {
                    result = "pfyh.png";
                }
                else if (BankName == "华夏银行")
                {
                    result = "hxyh.png";
                }

                return result;
            }
        }

        public string ShowRealName
        {
            get
            {
                if (UserId != 0)
                {
                    string sql = "select * from UserInfo where Id=" + UserId;
                    user = Util.ReaderToModel<UserInfo>(sql);
                    if (user != null)
                    {
                        return user.RealName;
                    }

                }
                return "";
            }
        }


        //用户组
        public string ShowGroup
        {
            get
            {
                if (GroupId != null)
                {
                    UserGroup userGroup = Util.GetEntityById<UserGroup>((int)GroupId);

                    if (userGroup != null)
                    {
                        return userGroup.Name;
                    }

                }

                return "";
            }
        }
    }
}
