//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using ShenZhen.Lottery.Public;

namespace ShenZhen.Lottery.Model
{
    using System;

    public partial class BettingRecord
    {
        public long Id { get; set; }
        public int UserId { get; set; }
        public string TryId { get; set; }
        public int lType { get; set; }
        public string Issue { get; set; }
        public int BetCount { get; set; }
        public string PlayName { get; set; }
        public string BetNum { get; set; }
        public decimal Peilv { get; set; }
        public int UnitMoney { get; set; }
        public int WinCount { get; set; }
        public decimal WinMoney { get; set; }
        public decimal TuiShui { get; set; }  //退水
        public int WinState { get; set; }
        public int Type { get; set; }
        public string NewOrderId { get; set; }
        public System.DateTime SubTime { get; set; }
        public decimal BetYE { get; set; }

        public decimal SY { get; set; }


        public UserInfo User { get; set; }

        public string UserName { get; set; }            //扩展


        public double ShowRebates
        {
            get
            {
                return Util.GetEntityById<UserInfo>(this.UserId).Rebates * 1000;
            }
        }


        //扩展字段
        public string ShowPeilv
        {

            get
            {
                if (lType == 3 || lType == 4)
                {
                    if (PlayName == "二中特")
                    {
                        return "50/25";
                    }
                    else if (PlayName == "三中二")
                    {
                        return "110/20";
                    }
                }

                return Peilv + "";
            }

        }

        public string ShowIssue
        {
            get
            {
                //string year = DateTime.Now.Year + "";

                //if (!this.Issue.StartsWith(year))
                //{
                //    return year + this.Issue;
                //}

                return this.Issue;
            }
        }

        public string ShowYE
        {
            get
            {
                if (BetYE == null)
                {
                    return "";
                }
                else
                {
                    return "" + BetYE;
                }
            }
        }



        //可赢金额
        public string PossibleWinMoney
        {
            get
            {
                if (lType == 3 || lType == 4)
                {
                    if (PlayName == "二中特")
                    {
                        return (this.UnitMoney * 50 * this.BetCount - this.BetCount * this.UnitMoney) + "/" + (this.UnitMoney * 25 * this.BetCount - this.BetCount * this.UnitMoney);
                    }
                    else if (PlayName == "三中二")
                    {
                        return (this.UnitMoney * 110 * this.BetCount - this.BetCount * this.UnitMoney) + "/" + (this.UnitMoney * 20 * this.BetCount - this.BetCount * this.UnitMoney);
                    }
                }



                return (this.UnitMoney * this.Peilv * this.BetCount - this.BetCount * this.UnitMoney).ToString();
            }
        }

        public string BetDetail
        {
            get { return this.PlayName + this.BetNum + "@" + this.ShowPeilv; }
        }

        public string ShowTime
        {
            get { return this.SubTime.ToString("yyyy-MM-dd HH:mm:ss"); }
        }

        public string ShowTime2
        {
            get { return this.SubTime.ToString("yy-MM-dd HH:mm:ss"); }
        }

        public string ShowTime3
        {
            get { return this.SubTime.ToString("MM-dd HH:mm:ss"); }
        }

        public string BetMoney
        {
            get
            {
                return (this.UnitMoney * this.BetCount).ToString("0.00");
            }
        }



        //输赢
        public decimal Shuying         //----------------待定
        {
            get
            {
                decimal result = 0;

                if (this.WinState > 2)
                {
                    //result = this.WinMoney + this.TuiShui - (this.BetCount * this.UnitMoney);
                    result = this.SY;
                }

                return result;
            }
        }



        public decimal ShuyingForBettingRecord         //----------------18-9-17
        {
            get
            {
                decimal result = 0;

                if (this.WinState > 2)
                {
                    result = this.WinMoney + this.TuiShui - (this.BetCount * this.UnitMoney);
                    //result = this.SY;
                }

                return result;
            }
        }



        public string ShuyingForBettingRecord2         //----------------19-8-18
        {
            get
            {
                decimal result = 0;

                if (this.WinState > 2)
                {
                    result = this.WinMoney + this.TuiShui - (this.BetCount * this.UnitMoney);
                    //result = this.SY;
                }

                string str = "";
                if (result >= 0)
                {
                    str = "<font style='color: #00b939;'>" + result + "</font>";
                }
                else
                {
                    str = "<font style='color: red;'>" + result + "</font>";
                }

                return str;


            }
        }





        public decimal ShuYing
        {
            get
            {
                if (this.WinState > 2)
                {
                    return this.WinMoney + this.TuiShui - (this.BetCount * this.UnitMoney);
                }

                return 0;
            }
        }

        public string ShuYing2
        {
            get
            {
                decimal result = 0;

                if (this.WinState > 2)
                {
                    //result = this.WinMoney + this.TuiShui - (this.BetCount * this.UnitMoney);
                    result = this.SY;
                }

                string str = "";
                if (result >= 0)
                {
                    str = "<font style='color: lime;'>" + result + "</font>";
                }
                else
                {
                    str = "<font style='color: red;'>" + result + "</font>";
                }

                return str;
            }
        }

        //开奖号码
        public string ShowWinNum
        {
            get
            {
                string sql = "select Num from LotteryRecord where Issue ='" + this.Issue + "' and lType=" + this.lType;

                object o = SqlHelper.ExecuteScalar(sql);

                if (o != null && o != DBNull.Value)
                {
                    return o.ToString();
                }

                return "---";
            }
        }


        public string ShowUserName
        {
            get
            {
                string sql = "select * from UserInfo where Id=" + UserId;

                User = Util.ReaderToModel<UserInfo>(sql);

                if (User != null)
                {
                    return User.UserName;
                }

                return "";
            }
        }


        public string ShowlTypeName
        {
            get
            {
                return Util.GetlTypeName(lType);
            }
        }


        public string ShowState
        {
            get
            {
                if (WinState == 1)
                {
                    return "未开奖";
                }
                else if (WinState == 2)
                {
                    return "已撤单";
                }
                else if (WinState == 3)
                {
                    return "已中奖";
                }
                else if (WinState == 4)
                {
                    return "未中奖";
                }
                else if (WinState == 5)
                {
                    return "和";
                }

                return "";
            }
        }
    }
}
