//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text;
using ShenZhen.Lottery.Public;

namespace ShenZhen.Lottery.Model
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;

    
    public partial class ChangeRecord
    {

        public int Id { get; set; }
        public int UserId { get; set; }
        public int Type { get; set; }

        public string Qian { get; set; }
        public string Hou { get; set; }
        public string Ip { get; set; }
        public string Operator { get; set; }
        
        public DateTime SubTime { get; set; }
        


        //扩展字段


        public string ShowTime
        {
            get
            {
                return this.SubTime.ToString("yyyy-MM-dd HH:mm:ss");
            }
        }


      
        public string ShowType
        {
            get
            {
                if (this.Type == 1)
                {
                    return "新增用户";
                }
                else if (this.Type == 2)
                {
                    return "修改用户";
                }
               


                return "";
            }
        }

        
    }
}
