//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using ShenZhen.Lottery.Public;
using System;
using System.Collections.Generic;

namespace ShenZhen.Lottery.Model
{
    public partial class LotteryRecord
    {
        public int Id { get; set; }
        public int lType { get; set; }
        public string Issue { get; set; }
        public string Num { get; set; }
        public System.DateTime SubTime { get; set; }
        public Nullable<bool> IsOpen { get; set; }
        public Nullable<System.DateTime> OpenTime { get; set; }


        //------------------------------------


        //开奖下面一排的信息
        public string ShowTeMa
        {
            get
            {
                string result = "";

                string[] arr = this.Num.Split(',');

                int num = int.Parse(arr[6]);


                int wei = int.Parse(arr[6].Substring(1, 1));


                int heshu = int.Parse(arr[6].Substring(0, 1)) + int.Parse(arr[6].Substring(1, 1));

                //result += 

                //1.大小

                if (num >= 1 && num <= 24)
                {
                    result += "小";
                }
                else if (num >= 24 && num <= 48)
                {
                    result += "大";
                }
                else if (num == 49)
                {
                    result += "和";
                }


                //2.单双
                if (num == 49)
                {
                    result += " 和";
                }
                else if (num % 2 == 0)
                {
                    result += " 双";
                }
                else
                {
                    result += " 单";
                }


                //3.特码尾数
                if (num == 49)
                {
                    result += " 和";
                }
                else if (wei <= 4)
                {
                    result += " 尾小";
                }
                else
                {
                    result += " 尾大";
                }


                //3.特码合数大小
                if (num == 49)
                {
                    result += " 和";
                }
                else if (heshu >= 7)
                {
                    result += " 合大";
                }
                else if (heshu <= 6)
                {
                    result += " 合小";
                }


                //3.特码合数单双
                if (num == 49)
                {
                    result += " 和";
                }
                else if (heshu % 2 == 0)
                {
                    result += " 合双";
                }
                else
                {
                    result += " 合单";
                }


                //3.家禽野兽
                if (Util.IsJiaQin(Util.GetShengxiaoByDigit(num)))
                {
                    result += " 家禽";
                }
                else
                {
                    result += " 野兽";
                }


                //3.波色
                result += " " + Util.GetColor2(arr[6]);



                return result;
            }
        }


        public string ShowOpenNumInfo
        {
            get
            {
                string result = "";
                string shengxiao = "";
                string yanse = "";

                foreach (string s in Num.Split(','))
                {
                    //生肖 波色
                    shengxiao = Util.GetShengxiaoByDigit(int.Parse(s));
                    yanse = Util.GetColor(s);

                    result += s + "-" + shengxiao + "-" + yanse + ",";
                }

                return result.TrimEnd(',');
            }
        }

        public string ShowTime
        {
            get { return this.SubTime.ToString("yyyy-MM-dd HH:mm:ss"); }
        }


        public string ShowTime2
        {
            get { return this.SubTime.ToString("MM-dd HH:mm:ss"); }
        }


        //开奖下面一排的信息
        public string ShowShengXiao
        {
            get
            {
                string result = "";

                string[] arr = this.Num.Split(',');

                result += Util.GetShengxiaoByDigit(int.Parse(arr[0])) + " " +
                                Util.GetShengxiaoByDigit(int.Parse(arr[1])) + " " +
                                Util.GetShengxiaoByDigit(int.Parse(arr[2])) + " " +
                                Util.GetShengxiaoByDigit(int.Parse(arr[3])) + " " +
                                Util.GetShengxiaoByDigit(int.Parse(arr[4])) + " " +
                                Util.GetShengxiaoByDigit(int.Parse(arr[5])) + " " +
                                Util.GetShengxiaoByDigit(int.Parse(arr[6]));
                return result;
            }
        }


        //生肖个数
        public string ShengXiaoCount
        {
            get
            {
                string[] arr = this.Num.Split(',');

                List<string> list = new List<string>();

                string sx = "";

                foreach (string s in arr)
                {
                    sx = Util.GetShengxiaoByDigit(int.Parse(s));

                    if (!list.Contains(sx))
                    {
                        list.Add(sx);
                    }
                }


                return list.Count + "只";
            }
        }

        //尾数个数
        public string WeiShuCount
        {
            get
            {
                string[] arr = this.Num.Split(',');

                List<string> list = new List<string>();

                string sx = "";

                foreach (string s in arr)
                {
                    sx = s.Substring(1, 1);

                    if (!list.Contains(sx))
                    {
                        list.Add(sx);
                    }
                }


                return list.Count + "个";
            }
        }


        //总和信息
        public string SumInfo
        {
            get
            {


                string result = "";

                int sum = 0;

                string[] arr = this.Num.Split(',');


                foreach (string s in arr)
                {

                    sum += int.Parse(s);
                }

                result += sum;

                if (sum >= 175)
                {
                    result += " 总大";
                }
                else
                {
                    result += " 总小";
                }


                if (sum % 2 == 0)
                {
                    result += " 总双";
                }
                else
                {
                    result += " 总单";
                }


                return result;
            }
        }



        public string ShowTypeName
        {
            get
            {
                return Util.GetlTypeName(lType);
            }
        }

    }
}
