//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using ShenZhen.Lottery.Public;

namespace ShenZhen.Lottery.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Message
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string AdminId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public DateTime SubTime { get; set; }
        public bool IsRead { get; set; }
        public bool IsDel { get; set; }
        public bool ToKeFu { get; set; }

        public int Type { get; set; }           //1.存款  2.出款 3.游戏   4.其他

        public bool IsReply { get; set; }
        public DateTime? ReplyTime { get; set; }
        public string ReplyContent { get; set; }



        public UserInfo user { get; set; }

        //扩展信息

        public string ShowTime
        {
            get { return this.SubTime.ToString("yyyy-MM-dd HH:mm:ss"); }
        }

        public string ShowReplyTime
        {
            get
            {
                if (ReplyTime != null)
                {
                    return ((DateTime)ReplyTime).ToString("yyyy-MM-dd HH:mm:ss");
                }

                return "";
            }
        }


        public string ShowDate
        {
            get { return this.SubTime.ToString("yyyy-MM-dd"); }
        }

        //public string ShowUserName
        //{
        //    get
        //    {
        //        string sql = "select * from UserInfo where Id=" + UserId;
        //        user = Util.ReaderToModel<UserInfo>(sql);

        //        if (user != null)
        //        {
        //            return user.UserName;
        //        }


        //        return "";
        //    }
        //}


        public string ShowAdminForSend
        {
            get
            {
                //AdminId
                return "管理员";
            }
        }



        public string ShowAdminForReply
        {
            get
            {
                //AdminId

                if (!string.IsNullOrEmpty(this.ReplyContent))
                {
                    return "管理员";
                }

                return "";
            }
        }


        public string ShowType
        {
            get
            {
                if (Type == 1)
                {
                    return "存款问题";
                }
                else if (Type == 2)
                {
                    return "出款问题";
                }
                else if (Type == 3)
                {
                    return "游戏问题";
                }
                else 
                {
                    return "其他";
                }
            }
        }

        public string DirectTop
        {
            get
            {
               

                    string sql = "select PId from UserInfo where Id=" + this.UserId;

                    int pId = 0;
                    
                    object o = SqlHelper.ExecuteScalar(sql);
                    if (o != DBNull.Value && o != null)
                    {
                        pId = (int) o;
                    }
                  

                    if (pId != 0)
                    {
                        sql = "select UserName from UserInfo where Id=" + pId;
                        o = SqlHelper.ExecuteScalar(sql);

                        if (o != DBNull.Value && o != null)
                        {
                            return o.ToString();
                        }
                      

                    }


                    return "";

                
            }
        }

    }
}
