//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShenZhen.Lottery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Position { get; set; }
        public string Content { get; set; }
        public bool IsTop { get; set; }
        public DateTime SubTime { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }


        //扩展字段

        public string ShowTime
        {
            get { return this.SubTime.ToString("yyyy-MM-dd HH:mm:ss"); }
        }


        public string ShowType
        {
            get
            {
                if (Type == "1")
                {
                    return "代理";
                }
                else if (Type == "2")
                {
                    return "会员";
                }
                else
                {
                    return "代理，会员";
                }

                return "";
            }
        }

        public string ShowPosition
        {
            get
            {
                if (Position == "1")
                {
                    return "跑马灯";
                }
                else if (Position == "2")
                {
                    return "弹出框";
                }
                else
                {
                    return "跑马灯，弹出框";
                }

                return "";
            }
        }


        public string ShowState
        {
            get
            {
                if (DateTime.Now > EndTime)
                {
                    return "已过期";
                }
                else
                {
                    return "--";
                }

            }
        }


    }



  

}
