//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using ShenZhen.Lottery.Public;

namespace ShenZhen.Lottery.Model
{
    using System;
    using System.Collections.Generic;

    public partial class RemindRecord
    {
       
        public int Id { get; set; }
        public int UserId { get; set; }
        public int Type { get; set; }           //1.上线提醒
        public System.DateTime SubTime { get; set; }

        public UserInfo user = null;
       

        //扩展字段
        public string ShowUserName
        {
            get
            {
                string sql = "select top(1)* from UserInfo where Id= " + UserId;
                user = Util.ReaderToModel<UserInfo>(sql);
                if (user != null)
                {
                    return user.UserName;
                }
                else
                {
                    return "";
                }
            }
        }

        public string ShowTime
        {
            get { return this.SubTime.ToString("yyyy-MM-dd HH:mm:ss"); }
        }

        public string ShowType
        {
            get
            {
                if (this.Type == 1)
                {
                    return "上线提醒";
                }
                else
                {
                    return "";
                }
            }
        }

        public string ShowDesc
        {
            get
            {
                if (this.Type == 1)
                {
                    return "特别用户" + user.UserName + "【上线】，敬请留意！";
                }
                else
                {
                    return "";
                }
            }
        }


        

    }
}
